"""
Django settings for django_trading_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*6l!g7rbv46-$#2w%#_i*5wz!g=4_d(a%i18^d2sw38vowk#%w"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "trading_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "django_trading_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_trading_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (if needed for uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

region = config('REGION', default='us')
sec_type = config('SECURITY_TYPE', default='etf')
SOURCE_DIR_NAME = os.environ.get('SOURCE_DIR', f'source/{region}/{sec_type}')

# Source directories
# DATA_DIR = BASE_DIR / 'source' / region / sec_type
DATA_DIR = BASE_DIR / SOURCE_DIR_NAME
TICKERS_DETAILS_PATH = DATA_DIR / 'tickers-details.csv'
TICKERS_PATH = DATA_DIR / 'tickers.csv'
RAW_DATA_PATH = DATA_DIR / 'raw_data.csv'
FULL_DF_PATH = DATA_DIR / 'full_df.csv'
SUMMARY_DF_PATH = DATA_DIR / 'summary_df.csv'
TOPN_PATH = DATA_DIR / 'top_n.csv'

# PORTFOLIO_NAMES = {
#     'source/au/stock': 'AU Stock',
#     'source/au/etf': 'AU ETF',
#     'source/us/stock': 'US Stock',
#     'source/us/etf': 'US ETF',
# }
#
# PORTFOLIO_NAME = PORTFOLIO_NAMES.get(SOURCE_DIR_NAME, 'Multi-Ticker')

PORTFOLIO_CONFIG = {
    'source/au/stock': {
        'name': 'AU Stock',
        'region': 'Australia',
        'currency': 'AUD',
        'currency_symbol': '$',
        'emoji': '🇦🇺'
    },
    'source/au/etf': {
        'name': 'AU ETF',
        'region': 'Australia',
        'currency': 'AUD',
        'currency_symbol': '$',
        'emoji': '🇦🇺'
    },
    'source/us/stock': {
        'name': 'US Stock',
        'region': 'United States',
        'currency': 'USD',
        'currency_symbol': '$',
        'emoji': '🇺🇸'
    },
    'source/us/etf': {
        'name': 'US ETF',
        'region': 'United States',
        'currency': 'USD',
        'currency_symbol': '$',
        'emoji': '🇺🇸'
    }
}

CURRENT_PORTFOLIO = PORTFOLIO_CONFIG.get(SOURCE_DIR_NAME, PORTFOLIO_CONFIG['source/us/etf'])
PORTFOLIO_NAME = CURRENT_PORTFOLIO['name']
PORTFOLIO_CURRENCY = CURRENT_PORTFOLIO['currency']
PORTFOLIO_CURRENCY_SYMBOL = CURRENT_PORTFOLIO['currency_symbol']

HUGGING_FACE_TOKEN = config('HUGGING_FACE_TOKEN', default='')
FINNHUB_API_KEY = config('FINNHUB_API_KEY', default='')

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 1 day

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'trading_app.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'trading_app': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {  # Also add Django's default logger
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)